/*
 * Team Members:
 * Rebecca Cowgill
 * Abigail Moore
 * 
 */

package clueGame;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;

public class GUIControlPanel extends JPanel {
	//the following are all the text fields that will be used
	private JTextField whoseTurn;
	private JTextField dieRoll;
	private JTextField guess;
	private JTextField response;
	
	JPanel whoseTurnPanel;
	JPanel rollDiePanel;
	JPanel guessPanel;
	JPanel guessResultPanel;
	JPanel accusationPanel;
	
	public GUIControlPanel() {
		setLayout(new GridLayout(2, 3));
		
		//Creates all panels and adds them to the larger panel
		whoseTurnPanel = whoseTurnPanel();
		add(whoseTurnPanel);
		
		JPanel panel = nextPlayerButtonPanel();
		add(panel);
		
		accusationPanel = makeAccusationButtonPanel();
		add(accusationPanel);
		
		rollDiePanel = rollDiePanel();
		add(rollDiePanel);
		
		guessPanel = guessPanel();
		add(guessPanel);
		
		guessResultPanel = guessResultPanel();
		add(guessResultPanel);
	}
	
	public void updateTurn(String turn) {
		Component[] components = whoseTurnPanel.getComponents();
		for (Component c : components) {
			if (c instanceof JTextField) {
				((JTextField) c).setText(turn);
			}
		}
	}
	
	public void updateRoll(int roll) {
		Component[] components = rollDiePanel.getComponents();
		for (Component c : components) {
			if (c instanceof JTextField) {
				((JTextField) c).setText(Integer.toString(roll));
			}
		}
	}
	
	private JPanel whoseTurnPanel() {
		JPanel panel = new JPanel();
		JLabel whoseTurnLabel = new JLabel("Whose Turn?");
		whoseTurn = new JTextField(15);
		//user shouldn't actually be able to edit this field
			//changed with next player button
		whoseTurn.setEditable(false);
		panel.add(whoseTurnLabel);
		panel.add(whoseTurn);
		return panel;
	}
	
	private JPanel nextPlayerButtonPanel() {
		JButton nextPlayer = new JButton("Next player");
		JPanel panel = new JPanel();
		
		//setting the gridlayout here is just to make the button fit the entire cell, serves no actual function
		panel.setLayout(new GridLayout(1,1));
		panel.add(nextPlayer);
		return panel;
	}
	
	private JPanel makeAccusationButtonPanel() {
		JButton makeAccusation = new JButton("Make an accusation");
		JPanel panel = new JPanel();
		
		//setting the gridlayout here is just to make the button fit the entire cell, serves no actual function
		panel.setLayout(new GridLayout(1,1));
		panel.add(makeAccusation);
		return panel;
	}
	
	private JPanel rollDiePanel() {
		JPanel panel = new JPanel();
		JLabel rollLabel = new JLabel("Roll");
		dieRoll = new JTextField(5);
		//user shouldn't actually be able to edit this field
			//will be randomly generated and displayed here
		dieRoll.setEditable(false);
		panel.add(rollLabel);
		panel.add(dieRoll);
		panel.setBorder(new TitledBorder (new EtchedBorder(), "Die"));
		return panel;
	}
	
	private JPanel guessPanel() {
		JPanel panel = new JPanel();
		JLabel guessLabel = new JLabel("Guess");
		guess = new JTextField(20);
		//user shouldn't actually be able to edit this field
			//will be generated by computer operated players
		guess.setEditable(false);
		panel.add(guessLabel);
		panel.add(guess);
		panel.setBorder(new TitledBorder (new EtchedBorder(), "Guess"));
		return panel;
	}
	
	private JPanel guessResultPanel() {
		JPanel panel = new JPanel();
		JLabel responseLabel = new JLabel("Response");
		response = new JTextField(10);
		//user shouldn't actually be able to edit this field
			//will be generated in response to player guesses
		response.setEditable(false);
		panel.add(responseLabel);
		panel.add(response);
		panel.setBorder(new TitledBorder (new EtchedBorder(), "Guess Result"));
		return panel;
	}
}
